### ISSUE TITLE
simple-manager bootstrap: AttributeError: 'str' object has no attribute 'update'

### ISSUE THREAD

**Issue by emepetres** [cloudify-cosmo/cloudify-manager-blueprints#586]
I'm trying to bootstrap a manager in a local Centos 7 vagrant (VirtualBox) machine using CLI 4.0 installed on windows 7.

The process goes as expected until it comes to this error:
**AttributeError: 'str' object has no attribute 'update' while deploying REST Security configuration file...**

I'm using simple-manager-blueprint defining the public and private vagrant machine ip, username, ssh key file. The virtual machine is a clean image of last Centos 7.

Below the pertinent log piece:
> CFY <manager> [rest_service_pqnb83.configure] Task started 'fabric_plugin.tasks.run_script'
> LOG <manager> [rest_service_pqnb83.configure] INFO: Deploying REST Service Configuration file...
> LOG <manager> [rest_service_pqnb83.configure] INFO: Deploying blueprint resource components/restservice/config/cloudify-rest.conf to /opt/manager/cloudify-res
> LOG <manager> [rest_service_pqnb83.configure] INFO: Deploying REST Security configuration file...
> out: Traceback (most recent call last):
> out:   File "/tmp/cloudify-ctx/scripts/tmphstwfu-configure.py-EUK9B1KS", line 174, in <module>
> out:     configure_restservice()
> out:   File "/tmp/cloudify-ctx/scripts/tmphstwfu-configure.py-EUK9B1KS", line 168, in configure_restservice
> out:     _deploy_security_configuration()
> out:   File "/tmp/cloudify-ctx/scripts/tmphstwfu-configure.py-EUK9B1KS", line 72, in _deploy_security_configuration
> out:     current_props.update(security_configuration)
> out: AttributeError: 'str' object has no attribute 'update'
> out:
> CFY <manager> [logstash_hwo9u8->rabbitmq_pdw0pf|preconfigure] Task started 'fabric_plugin.tasks.run_script'
> CFY <manager> [rest_service_pqnb83.configure] Task failed 'fabric_plugin.tasks.run_script' -> run() received nonzero return code 1 while executing!

**Comment by tehasdf** [comment]
Looks like you're using the master branch/4.0.1 blueprint? Please use a 4.0.1/master branch CLI with that, and use blueprints from the 4.0 tag when working with a 4.0 CLI

**Comment by emepetres** [comment]
Thanks, @tehasdf. Indeed I was trying with last blueprints because when using ones 4.0 tag I get a different error:
**File: cloudify-stage-*.tgz does not exist in sources path: /opt/cloudify/sources**

> LOG <manager> [stage_72fo29.create] INFO: Installing Cloudify Stage (UI)...
> out: File: cloudify-stage-*.tgz does not exist in sources path: /opt/cloudify/sources
> out: Traceback (most recent call last):
> out:   File "/tmp/cloudify-ctx/scripts/tmp5nnxpu-create.py-3NZI50I1", line 70, in <module>
> out:     main()
> out:   File "/tmp/cloudify-ctx/scripts/tmp5nnxpu-create.py-3NZI50I1", line 67, in main
> out:     install_stage()
> [192.168.56.10] out:   File "/tmp/cloudify-ctx/scripts/tmp5nnxpu-create.py-3NZI50I1", line 54, in install_stage
> [192.168.56.10] out:     STAGE_SERVICE_NAME)
> [192.168.56.10] out:   File "/tmp/cloudify-ctx/scripts/utils.py", line 427, in download_cloudify_resource
> [192.168.56.10] out:     render=False)
> [192.168.56.10] out:   File "/tmp/cloudify-ctx/scripts/utils.py", line 1105, in create
> [192.168.56.10] out:     resource_name)
> [192.168.56.10] out:   File "/tmp/cloudify-ctx/scripts/utils.py", line 1244, in _get_local_file_path
> [192.168.56.10] out:     local_filepath = get_filepath_from_pkg_name(resource_name)
> [192.168.56.10] out:   File "/tmp/cloudify-ctx/scripts/utils.py", line 572, in get_filepath_from_pkg_name
> [192.168.56.10] out:     format(filename, CLOUDIFY_SOURCES_PATH))
> [192.168.56.10] out:   File "/tmp/cloudify-ctx/cloudify.py", line 234, in abort_operation
> [192.168.56.10] out:     subprocess.check_call(cmd)
> [192.168.56.10] out:   File "/usr/lib64/python2.7/subprocess.py", line 542, in check_call
> [192.168.56.10] out:     raise CalledProcessError(retcode, cmd)
> [192.168.56.10] out: subprocess.CalledProcessError: Command '['ctx', 'abort_operation', 'File: cloudify-stage-*.tgz does not exist in sources path: /opt/cloudify/sources']' returned non-zero exit status 1
> [192.168.56.10] out:
> 2017-05-10 10:55:41.158  CFY <manager> [stage_72fo29.create] Task failed 'fabric_plugin.tasks.run_script' -> File: cloudify-stage-*.tgz does not exist in sources path: /opt/cloudify/sources
> 2017-05-10 10:55:41.278  CFY <manager> 'install' workflow execution failed: Workflow failed: Task failed 'fabric_plugin.tasks.run_script' -> File: cloudify-stage-*.tgz does not exist in sources path: /opt/cloudify/sources
> Bootstrap failed! (Workflow failed: Task failed 'fabric_plugin.tasks.run_script' -> File: cloudify-stage-*.tgz does not exist in sources path: /opt/cloudify/sources)
> Executing teardown due to failed bootstrap...
>

**Comment by emepetres** [comment]
Actually I'm closing this issue and creating a new one, as the error I mention in the last post is different from the one that opened the issue.
